site_name: "F# Language Specification"
site_url: https://fsharp.github.io/fslang-spec
repo_url: https://github.com/fsharp/fslang-spec
copyright: "Copyright © 2005-2025 F# contributors. Made available under the <a href='https://creativecommons.org/licenses/by/4.0/'>Creative Commons CC-by 4.0</a> licence."
theme:
  name: material
  icon:
    logo: simple/fsharp
  favicon: fsharp128.png

markdown_extensions:
  - pymdownx.superfences

nav:
